// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eacvkpbbbrojmimyxvxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhY3ZrcGJiYnJvam1pbXl4dnhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTcxMjksImV4cCI6MjA3MTA5MzEyOX0.oD2PoL2bk3DKNM6l4t7kFppjYTYQB2cOeDKbT32hNeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});